language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: serveadmin@octoblu.com
  api_key:
    secure: T093idUGU+V+B80JL3nRDB8hAaIJx6vl0tukHiDV4oGz+MBPCQLLziyKnjLoN3FpN3kZs2yPFmPvrhhc4FD1BAoOBR72fPexzUt2ZKSUBIpPwfLjGmJhYDi+gEE3+7V9w0V9SpH/ltehUggc3E2bIMylq8WSg9dNVn0sED7ql0mQmP9a6436aAhYMSvCQn+0oSmUJb7wniaXzOfXpKckVditmwCQGqQrHelHDGR1O+H4Du5zO7cdIegzqnujJTN/LXrcWO2NcrYZd4ku25P8PH8JC6kKS8fx0/ROTNgo5ac5Hv5bBnZqKrgG+Ei1u3pnDXblmwRA4q7aUqN1fag0/T+lDT9GYaur4s10UBCN4/vc9EV20fSKTfDHf68TYJxBFbfQDDiaZK4PCI869hwseEE5q+1XEwQp+4RQwRYMagy2NIWQgYzY94aTe9EvoRkoqiMlbeUK7ZIayM8pOHJ1/NnmdkClgajyHEmDiNJgckmNQ9H3BI9Hx62CtaI3CyzV3UyBfe/x3hdn9qq50o6/UL7JvDfXVzW18TDBZaHiDZaSmj3IfFPmpEBxrZTaAQrmurQXeEouv46CQy0r9PBDNbvzVGRz+7NH5v7Plogz43FmjML+lqVwLLE/X6fcm/mCgW3m3kbbeCsg0aGr6pIrh6UuTeLSHvSoH6PniqWMHxQ=
  on:
    tags: true
    repo: octoblu/nanocyte-configuration-generator
