language: node_js
node_js:
- '0.11'
addons:
  code_climate:
    repo_token: db0ec1d21d46f280154cab7d35f97131c6a6769cbfb9bd0d19d8675611d16de7
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: FRtdiskdCDUK31wr9w9gkejhp6mo4Z8UMVJwP67XM3lwzJXmSLNcpSGI8KrsEpc56okRcm25RHHq0SkQzWWkK+T7lVt68XUn1YMKcrY+vUcoWTeQiCkfQvUtovT3tVdb7DHqIhk1XvggsjQJjlTX4ZI/zo+0yZtO+OT5NQEC5QcCNGZUkrYAYf6ZusIZNSlb870QQV+UPvTKs5NFCB52hH6k++m2wH8fWOxqUJ+/w2tGw2SawCsSUrtOmrf4KHExTFS4WnoIOwj7KjYX6HoT+8PZT3L8z7MndzJxxvVxncdlvflq7j9D0mnXlGiJh/vLZV8Ly2ItMK3QQ9QrXXqj7Bh5BabaQSpGjNxnZeQJdIbhXm9jRlSOb8mPXuhPFJkRAkxYtZ1w+iHyFDHOcQ4R1HTnulTok9DGgG+Lv3AUacUvsF/T77MvotDoSJ8QULEAyptl6fPHgU1uo2RIEgrAaGncY+6luI1oH1Unis7KU+Pioq5oklulSy7r5dmXcNlrvQRK3+BC7xchab/gz7LvqNiXUhcpa//ohhHhwNOLTRS1mJgXj85nwEZ4PaoUbM895I1vsQ4VTpPIAGpoiIvg043fIsQzDsxWCLhXSSWof9s7eMa+wtYN0m+VPw3WrPaHfEn8JieFs31yVXsXCzUtg8WJ97C8Eyye6wffet4XoIY=
  on:
    tags: true
    branches: true
    repo: octoblu/nanocyte-configuration-generation
